.RECIPEPREFIX +=
ATLAS=/data/vision/polina/projects/wmh/razvan/gasros_affine_transformed_cropped_32_32_32/test/atlas.npz
DATA_FOLDER=/data/vision/polina/projects/wmh/razvan/gasros_affine_transformed_cropped_32_32_32/test

raz_test:
    python3 train.py $(DATA_FOLDER) --atlas_file $(ATLAS) --gpu 0